### ISSUE TITLE
Memory corruptions and abort in QBE

### ISSUE THREAD

**Issue by elManto** [michaelforney/qbe#2]
Recently I found some ASAN/UBSAN violations in qbe. Here I attach the ASAN report and the crashing inputs. To reproduce it is sufficient to compile with address sanitizer enabled and execute: "./qbe <crashing_input>".

[qbe.tar.gz](https://github.com/michaelforney/qbe/files/6849017/qbe.tar.gz)

**Comment by elManto** [comment]
Ah sorry, I forgot to specify that I was using this commit e0b94a3d6a

**Comment by michaelforney** [comment]
Thanks a bunch for doing this work and finding all these inputs. Would you mind sending this along to the recently created QBE mailing list? ~mpu/qbe@lists.sr.ht
